import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

export function generateTransferPDF({ type, techName, warehouseNumber, notes, date, items }) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' })

  const isReturn = type === 'warehouse_return'
  const title = isReturn ? 'Warehouse Return' : 'Truck Transfer'
  const accentColor = isReturn ? [45, 106, 79] : [26, 26, 46]
  const formattedDate = new Date(date).toLocaleString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric',
    hour: '2-digit', minute: '2-digit'
  })

  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 20

  doc.setFillColor(...accentColor)
  doc.rect(0, 0, pageWidth, 28, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('DHP T2T', margin, 12)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(title.toUpperCase(), margin, 21)

  doc.setFontSize(9)
  doc.text(formattedDate, pageWidth - margin, 12, { align: 'right' })

  doc.setTextColor(30, 30, 30)
  doc.setFontSize(10)

  let y = 40
  const labelX = margin
  const valueX = margin + 42

  const infoRows = [
    ['Tech Name:', techName],
    ['Warehouse #:', warehouseNumber],
    ['Date / Time:', formattedDate],
    ...(notes ? [['Notes:', notes]] : []),
  ]

  infoRows.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(80, 80, 80)
    doc.text(label, labelX, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(20, 20, 20)
    doc.text(String(value), valueX, y)
    y += 7
  })

  y += 3
  doc.setDrawColor(...accentColor)
  doc.setLineWidth(0.5)
  doc.line(margin, y, pageWidth - margin, y)
  y += 6

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(...accentColor)
  doc.text('Parts List', margin, y)
  y += 4

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [['Part Number', 'Description', 'Qty']],
    body: items.map(item => [
      item.part_number || item.partNumber || '',
      item.description || '',
      String(item.quantity),
    ]),
    headStyles: {
      fillColor: accentColor,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10,
    },
    bodyStyles: { fontSize: 9, textColor: [30, 30, 30] },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    columnStyles: {
      0: { cellWidth: 40 },
      1: { cellWidth: 'auto' },
      2: { cellWidth: 20, halign: 'center' },
    },
  })

  const pageHeight = doc.internal.pageSize.getHeight()
  doc.setFontSize(8)
  doc.setTextColor(160, 160, 160)
  doc.setFont('helvetica', 'normal')
  doc.text('Generated by DHP T2T', pageWidth / 2, pageHeight - 10, { align: 'center' })

  return doc.output('blob')
}

export function generateCombinedPDF(type, records) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' })

  const isReturn = type === 'warehouse_return'
  const title = isReturn ? 'Warehouse Returns' : 'Truck Transfers'
  const accentColor = isReturn ? [45, 106, 79] : [26, 26, 46]
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const today = new Date().toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  })

  doc.setFillColor(...accentColor)
  doc.rect(0, 0, pageWidth, 28, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text('DHP T2T', margin, 12)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text(`DAILY SUMMARY — ${title.toUpperCase()}`, margin, 21)

  doc.setFontSize(9)
  doc.text(today, pageWidth - margin, 12, { align: 'right' })
  doc.text(`${records.length} record${records.length !== 1 ? 's' : ''}`, pageWidth - margin, 21, { align: 'right' })

  let y = 40

  records.forEach((record, index) => {
    const items = type === 'warehouse_return'
      ? (record.items || [])
      : (record.transfer_items || [])

    const formattedDate = new Date(record.created_at).toLocaleString('en-US', {
      month: 'long', day: 'numeric', year: 'numeric',
      hour: '2-digit', minute: '2-digit',
    })

    const notes = record.reason || record.notes || ''
    const estimatedHeight = 14 + (items.length * 8) + 30

    if (y + estimatedHeight > pageHeight - 20 && index > 0) {
      doc.addPage()
      y = 20
    }

    doc.setFillColor(...accentColor.map(c => Math.min(255, c + 40)))
    doc.rect(margin, y, pageWidth - margin * 2, 8, 'F')

    doc.setTextColor(255, 255, 255)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.text(`#${index + 1} — ${record.tech_name}`, margin + 3, y + 5.5)
    doc.text(`WH: ${record.warehouse_number}`, pageWidth - margin - 3, y + 5.5, { align: 'right' })
    y += 11

    doc.setTextColor(80, 80, 80)
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(8)
    doc.text(`Date: ${formattedDate}`, margin + 2, y)
    if (notes) {
      const splitNotes = doc.splitTextToSize(`Notes: ${notes}`, pageWidth - margin * 2 - 4)
      doc.text(splitNotes, margin + 2, y + 5)
      y += 5 * splitNotes.length + 3
    }
    y += 6

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Part Number', 'Description', 'Qty']],
      body: items.map(item => [
        item.part_number || item.partNumber || '—',
        item.description || '—',
        String(item.quantity || '—'),
      ]),
      headStyles: {
        fillColor: accentColor,
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 8,
      },
      bodyStyles: { fontSize: 8, textColor: [30, 30, 30] },
      alternateRowStyles: { fillColor: [245, 247, 250] },
      columnStyles: {
        0: { cellWidth: 40 },
        1: { cellWidth: 'auto' },
        2: { cellWidth: 20, halign: 'center' },
      },
      didDrawPage: () => {
        doc.setFontSize(7)
        doc.setTextColor(160, 160, 160)
        doc.text('Generated by DHP T2T', pageWidth / 2, pageHeight - 8, { align: 'center' })
      },
    })

    y = doc.lastAutoTable.finalY + 10

    if (index < records.length - 1) {
      doc.setDrawColor(220, 220, 220)
      doc.setLineWidth(0.3)
      doc.line(margin, y - 4, pageWidth - margin, y - 4)
    }
  })

  doc.setFontSize(7)
  doc.setTextColor(160, 160, 160)
  doc.setFont('helvetica', 'normal')
  doc.text(`Generated by DHP T2T — ${today}`, pageWidth / 2, pageHeight - 8, { align: 'center' })

  return doc.output('blob')
}